# Generated by Django 3.0.2 on 2020-01-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0002_auto_20200119_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miejsce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miasto', models.CharField(max_length=50)),
                ('ulica', models.CharField(max_length=50)),
                ('numer', models.CharField(max_length=10)),
                ('kod', models.CharField(max_length=6)),
                ('telefon', models.IntegerField(max_length=9)),
                ('adres', models.CharField(max_length=120)),
            ],
        ),
    ]
