# Generated by Django 3.0.2 on 2020-01-20 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wypozyczalnia', '0003_miejsce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miejsce',
            name='telefon',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Rezerwacje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('miejsce_odbioru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odbior', to='wypozyczalnia.Miejsce')),
                ('miejsce_zwrotu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zwrot', to='wypozyczalnia.Miejsce')),
                ('samochod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.Samochod')),
            ],
        ),
    ]
