# Generated by Django 3.0.2 on 2020-01-20 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0004_auto_20200120_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezerwacje',
            name='data_odbioru',
            field=models.DateField(default=datetime.date(2020, 1, 20)),
        ),
        migrations.AddField(
            model_name='rezerwacje',
            name='data_zwrotu',
            field=models.DateField(default=datetime.date(2020, 1, 20)),
        ),
    ]
